### ISSUE TITLE
mms vms hlr push

### ISSUE THREAD

**Issue by KernelFolla** [smsapi/smsapi-python-client#19]
Hello,

is there any reason to disable mms vms hlr and push in SmsApiComClient?
Actually it works calling them directly with Hlr(client).check_number(number='...')

**Comment by in-void** [comment]
Hi, 
The reason why mms and vms are disabled in ComClient is that we do not provide this services outside of Poland. In case of Push is a temporary business decision. Hlr can be enabled.
