### ISSUE TITLE
invalid escape sequence after update to python 3.12

### ISSUE THREAD

**Issue by maxbuegler** [smsapi/smsapi-python-client#35]
`/root/.cache/pypoetry/virtualenvs/cogthera-de-backend-auth-9TtSrW0h-py3.12/lib/python3.12/site-packages/smsapi/endpoint.py:64: SyntaxWarning: invalid escape sequence '\w'  placeholder_pattern = re.compile('{\w+}')`

**Comment by mpawikowski** [comment]
Hello,

Forwarded to our IT department

**Comment by in-void** [comment]
Resolved in 2.9.6
