### ISSUE TITLE
Status 200 dla QUEUE?

### ISSUE THREAD

**Issue by user0007** [smsapi/smsapi-python-client#7]
Dlaczego po wysłaniu SMS, status kodu dla rezultatu QUEUE to 200? Według dokumentacji powinien być 409: https://www.smsapi.pl/statusy-wiadomosci

res.status_code, res.status
200 QUEUE

**Comment by in-void** [comment]
Witam. Parametr 'status_code' zawiera kod odpowiedzi HTTP. 
Pozdrawiam
