### ISSUE TITLE
smsapi-python-client PyPI

### ISSUE THREAD

**Issue by user0007** [smsapi/smsapi-python-client#8]
Jest szansa na oznaczenie biblioteki numerkiem i wrzucenie do PyPI? Albo chociaż tagowanie wersji w gitcie? 

Dodając smsapi-python-client do requirements projektu, za każdym razem (local, CI, produkcja) jest ryzyko pobrania innej wersji!

**Comment by iyn** [comment]
+1

**Comment by in-void** [comment]
It was done. Check this out https://pypi.python.org/pypi/smsapi-client.
